---
vars:
  -
    name: SERVICE_NAME
    values:
      -
        context:
          TEST_VAR: local_news
        value: news
      -
        context:
          TEST_VAR: local_payment
        value: payment
      -
        context: ~
        value: user
  -
    name: TEST_VAR
    values:
      -
        context: ~
        value: global
